[project]
name = "training-calculator"
version = "0.0.1"
dependencies = ["python-barcode"]

[project.optional-dependencies]
dev = ["build", "pytest", "pytest-cov", "coverage", "pipdeptree", "twine"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
